name: Android CI

# Trigger the workflow on pull requests to main and develop branches
on:
  pull_request:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: "Manual Android Build"
        description: "Release Notes"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get last commit hash code
        id: get_commit_hash_code
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "COMMIT_HASH_CODE=${{ github.sha }}" >> $GITHUB_ENV
          else
            echo "COMMIT_HASH_CODE=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          fi

      - name: Extract versionCode and versionName
        id: extract_version_code_name
        run: |
          # Extract versionCode
          VERSION_CODE=$(grep -oP 'versionCode \K\d+' app/build.gradle)
          echo "VERSION_CODE=${VERSION_CODE}" >> $GITHUB_ENV
          
          # Extract VersionName
          VERSION_NAME=$(grep -oP '(?<=versionName ")[^"]*' app/build.gradle)
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

      - name: Modify versionCode and versionName
        id: modify_version_code_name
        run: |
          # Modify versionCode
          TIMESTAMP=$(date +%s)  # Get the current timestamp in seconds
          CURRENT_MINUTES=$((TIMESTAMP / 60))  # Convert to minutes
          NEW_VERSION_CODE=$((CURRENT_MINUTES - 28650))  # Subtract 228650 from the current minutes
          echo "New versionCode: ${NEW_VERSION_CODE}"

          # Modify versionName
          NEW_VERSION_NAME="${VERSION_NAME}-${{ github.event.pull_request.number }}-${{ env.COMMIT_HASH_CODE }}"
          echo "New version name: ${NEW_VERSION_NAME}"
          
          # Update versionCode in build.gradle
          sed -i "s/versionCode \d\+/versionCode ${NEW_VERSION_CODE}/" app/build.gradle
          
          # Update the versionName in build.gradle
          sed -i "s/versionName \".*\"/versionName \"${NEW_VERSION_NAME}\"/" app/build.gradle

      - name: Verify changes
        run: |
          # Print updated versionCode and versionName from build.gradle
          grep 'versionCode' app/build.gradle
          grep 'versionName' app/build.gradle

#      - name: Determine Release Notes
#        id: release_notes
#        run: |
#          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
#            echo "RELEASE_NOTES=${{ inputs.release_notes }}" >> $GITHUB_ENV
#          else
#            echo "RELEASE_NOTES=${{ github.event.pull_request.title }}$'\n'${{ github.event.pull_request.body }}" >> $GITHUB_ENV
#          fi
#        shell: bash
#
#      - name: Print Release Notes
#        run: |
#          echo "Release Notes:"
#          echo ${{ env.RELEASE_NOTES }}

#      # Step 2: Set up JDK (Java 11 or 17 depending on your Android project setup)
#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'  # You can also use 'adopt' or 'temurin'
#          java-version: '17'    # Or '17' if your project uses Java 17
#
#      # Step 3: Cache Gradle dependencies to speed up builds
#      - name: Cache Gradle packages
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            gradle-${{ runner.os }}-
#
#      # Step 4: Set up the Android SDK
#      - name: Set up Android SDK
#        uses: android-actions/setup-android@v3
#
#      # Step 5: Build the Android project
#      - name: Build with Gradle
#        run: ./gradlew build
